cxx_binary(
    name = "main",
    srcs = ["main.cpp", "library.cpp"],
)

cxx_library(
    name = "print",
    srcs = ["library.cpp"],
    exported_headers = glob(["**/*.hpp"]),
    visibility = ["PUBLIC"],
)
